"""
RAO-AGI scoring utility.

Processes submission files generated by the evaluation harness and calculates
accuracy against provided solutions.

Usage:
    python score.py <submission_file> [--solutions-dir data/training]

Parameters:
    submission_file: JSON object mapping task IDs to column selections.
    solutions_dir:   Directory containing task JSON definitions with embedded solutions.
"""

import json
import os
import sys
import argparse

def load_solutions(solutions_dir):
    """
    Loads task solutions from the specified directory.
    
    Args:
        solutions_dir (str): Path to directory containing task JSON files.
        
    Returns:
        dict: Mapping of task IDs to their respective solutions.
    """
    solutions = {}
    if not os.path.isdir(solutions_dir):
        print(f"Error: solutions directory not found: {solutions_dir}", file=sys.stderr)
        sys.exit(1)
    for filename in sorted(os.listdir(solutions_dir)):
        if not filename.endswith(".json"):
            continue
        path = os.path.join(solutions_dir, filename)
        with open(path) as f:
            task = json.load(f)
        if "solution" not in task:
            continue
        solutions[task["id"]] = task["solution"]
    return solutions

def load_submission(submission_path):
    """
    Loads a submission file for evaluation.
    
    Args:
        submission_path (str): Path to the submission JSON file.
        
    Returns:
        dict: The parsed submission data.
    """
    if not os.path.isfile(submission_path):
        print(f"Error: submission file not found: {submission_path}", file=sys.stderr)
        sys.exit(1)
    with open(submission_path) as f:
        submission = json.load(f)
    if not isinstance(submission, dict):
        print("Error: submission format must be a JSON object mapping task IDs to column choices.", file=sys.stderr)
        sys.exit(1)
    return submission

def calculate_score(submission, solutions):
    """
    Calculates the accuracy score of a submission against the solutions.
    
    Args:
        submission (dict): Submitted task responses.
        solutions (dict): Expected task solutions.
        
    Returns:
        tuple: (correct_count, total_count, missing_ids, incorrect_details)
    """
    correct = 0
    total = 0
    missing = []
    wrong = []

    for task_id, expected in sorted(solutions.items()):
        total += 1
        if task_id not in submission:
            missing.append(task_id)
            continue
        answer = str(submission[task_id])
        if answer == str(expected):
            correct += 1
        else:
            wrong.append((task_id, answer, expected))

    return correct, total, missing, wrong

def main():
    """Main entry point for the scoring utility."""
    parser = argparse.ArgumentParser(description="Score a RAO-AGI submission.")
    parser.add_argument("submission", help="Path to the submission JSON file.")
    parser.add_argument(
        "--solutions-dir",
        default="data/training",
        help="Directory containing task definitions with solutions. Default: data/training",
    )
    args = parser.parse_args()

    solutions = load_solutions(args.solutions_dir)
    submission = load_submission(args.submission)

    if not solutions:
        print("Error: No valid tasks with solutions found in the provided directory.", file=sys.stderr)
        sys.exit(1)

    correct, total, missing, wrong = calculate_score(submission, solutions)

    print(f"\nEvaluation Results")
    print(f"------------------")
    print(f"Total tasks evaluated : {total}")
    print(f"Correct responses     : {correct}")
    print(f"Incorrect responses   : {len(wrong)}")
    print(f"Unanswered tasks      : {len(missing)}")
    print(f"Final Score           : {correct}/{total} ({100 * correct / total:.1f}%)")

    if wrong:
        print(f"\nIncorrect response details:")
        for task_id, answer, expected in wrong:
            print(f"  {task_id}: submitted={answer}, expected={expected}")

    if missing:
        print(f"\nUnanswered tasks:")
        for task_id in missing:
            print(f"  {task_id}")

    return 0

if __name__ == "__main__":
    sys.exit(main())
